### ISSUE TITLE
de-cruft & improve quest

### ISSUE THREAD

**Issue by tcql** [tcql/greiner-hormann#20]
Wrapping up a couple of big priorities that I've partially started on and hope to tackle a bit more during the holiday break 
- [ ] [Determine likely operations up front](https://github.com/tcql/greiner-hormann/issues/16) using [bbox tests](https://github.com/tcql/greiner-hormann/issues/17) and simple logic 
  - Ex: In intersect mode, Subject Boundary + Clip Boundary require intersection. Subject Boundary + Clip Hole require subtraction. We know this from the beginning and can calculate ahead
  - Bbox checks let us avoid work, which is :+1::rocket:
- [ ] [Convert arrays to `Ring` and `Vector` up front](https://github.com/tcql/greiner-hormann/issues/8#issuecomment-100814881). Only convert back to arrays during output.
- [ ] Change input format to use formalized objects
  - Following GeoJSON style means that the algorithm has to have intrinsic knowledge (that is unspecified!) and has to sort out whether you passed it a multipolygon with 3 rings or a polygon with one ring and 2 holes
  - Instead I want to implement a `Polygon(ring, [holes])` class that can be used to generate proper input structures. 
- [ ] Internalize `pointInPolygon`, `isClockwise` and other utility methods to [make GH dependencyless](https://github.com/tcql/greiner-hormann/issues/6)

I think all in all this will help clean up and narrow down the focus, which will make it easier to reason about better degeneracy handling and let us kill failing degenerate cases.
